### ISSUE TITLE
Runtime error on python 3.10

### ISSUE THREAD

**Issue by akashdev2016** [airplanedev/cli#644]
Hello everyone.
Recently I've deployed the python script on airplane. 
It was working well with python 3.9, but now version 3.10 seems to be used on airplane.
So I meet the following error on runtime.

`  File "/usr/local/lib/python3.10/site-packages/shareplum/__init__.py", line 6, in <module>
    from .site import Site  # noqa: F401
  File "/usr/local/lib/python3.10/site-packages/shareplum/site.py", line 8, in <module>
    from requests_toolbelt import SSLAdapter
  File "/usr/local/lib/python3.10/site-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/usr/local/lib/python3.10/site-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/usr/local/lib/python3.10/site-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/usr/local/lib/python3.10/site-packages/requests_toolbelt/_compat.py", line 11, in <module>
    from collections import Mapping, MutableMapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
Run failed`

I found problem on google, but some manual modification is needed on python package - `collections`
https://github.com/tensorflow/tensorboard/issues/5478

Thanks for your time.

**Comment by colinking** [comment]
Hey @akashdev2016! Apologies for the delay in getting back to you. We don't check GitHub issues often, so you're generally better off sending an email to `support@airplane.dev` or messaging us through the Intercom widget in-app.

As you noticed, we did recently upgrade the default Python version to `3.10` and new builds picked up this change automatically. The breaking changes were an oversight on our behalf, and you weren't the only one who hit them. Going forward, we're making a few changes to avoid this issue with future Python upgrades. All tasks will be locked to the latest supported minor Python version when created, and then you can opt-in to upgrade to a more recent version of Python at your own pace. Those changes will land before we ship Python 3.11 support and will not require you to make any changes to your tasks.
